version: '2'
services:
    build:
        build: 
            context: ./docker
            dockerfile: Dockerfile
            args:
                - http_proxy
                - HTTP_PROXY
                - HTTPS_PROXY
                - https_proxy
                - no_proxy
                - NO_PROXY
        volumes:
            - ./:/mnt:rw
    proxytest:
        image: alpine:3.10
        environment:
            - http_proxy
            - HTTP_PROXY
            - HTTPS_PROXY
            - https_proxy
            - no_proxy
            - NO_PROXY
