#!/bin/sh

APPDIR="$(dirname "$(readlink -f "$0")")"
SOMMELIER=$(which sommelier 2>/dev/null && echo "--scale=0.5 --x-display=:0" || echo "")
$SOMMELIER java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/multipaint.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar" multipaint "$@"
